ports:
- port: 3007
tasks:
- command: npm update
- command: npm audit fix
- command: mkdir /workspace/bitbus/twetch
- command: cd /workspace/bitbus/twetch
- command: cd /workspace/bitbus
- command: node index start /workspace/bitbus/twetch/twetchbus.json
- command: node index serve /workspace/bitbus/twetch/twetchbus.json
